# https://github.com/TimonVS/pr-labeler-action
feature: ['feature/*', 'feat/*']
improve: 'improve/*'
change: 'change/*'
fix: 'fix/*'
docs: 'docs/*'
style: 'style/*'
refactor: 'refactor/*'
perf: 'perf/*'
test: 'test/*'
build: 'build/*'
ci: 'ci/*'
chore: 'chore/*'
