template: $CHANGES
name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
exclude-labels:
  - "dependencies"
  - "skip-changelog"
autolabeler:
  - label: "enhancement"
    branch:
      - '/feature\/.+/'
      - '/feat\/.+/'
  - label: "bug"
    branch:
      - '/fix\/.+/'
  - label: "ci"
    files:
      - .github/**/*
  - label: "breaking-change"
    title:
      - "/.+!:.+/"
  - label: "board"
    files:
      - lib/board/**/*
  - label: "iot"
    files:
      - lib/iot/**/*
  - label: "blog"
    files:
      - lib/blog/**/*
  - label: "storage"
    files:
      - lib/storage/**/*
  - label: "ci"
    files:
      - .github/**/*
  - label: "android"
    files:
      - android/**/*
  - label: "web"
    files:
      - web/**/*
  - label: "windows"
    files:
      - windows/**/*
categories:
  - title: 💥 破坏性变更
    labels:
      - breaking-change
  - title: 🚀 新功能
    labels:
      - enhancement
  - title: 🐛 Bug 修复
    labels:
      - bug
  - title: 💫 杂项
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch
