name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: 'Added'
    labels:
      - 'enhancement'
  - title: 'Changed'
    labels:
      - 'change'
  - title: 'Deprecated'
    labels:
      - 'deprecation'
  - title: 'Removed'
    labels:
      - 'removed'
  - title: 'Fixed'
    labels:
      - 'bug'
  - title: 'Security'
    labels:
      - 'security'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  $CHANGES
