name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
autolabeler:
  - label: 'bug'
    branch:
      - '/fix\/.+/'
  - label: 'change'
    branch:
      - '/change\/.+/'
  - label: 'enhancement'
    branch:
      - '/feature\/.+/'
      - '/feat\/.+/'
      - '/improve\/.+/'
  - label: 'docs'
    branch:
      - '/docs\/.+/'
  - label: 'board'
    files:
      - lib/board/**/*
  - label: 'iot'
    files:
      - lib/iot/**/*
  - label: 'blog'
    files:
      - lib/blog/**/*
  - label: 'storage'
    files:
      - lib/storage/**/*
  - label: 'ci'
    files:
      - .github/**/*
  - label: 'android'
    files:
      - android/**/*
  - label: 'web'
    files:
      - web/**/*
  - label: 'windows'
    files:
      - windows/**/*
categories:
  - title: 'Added'
    labels:
      - 'enhancement'
      - 'feature'
  - title: 'Changed'
    labels:
      - 'improve'
      - 'change'
  - title: 'Deprecated'
    labels:
      - 'deprecation'
  - title: 'Removed'
    labels:
      - 'removed'
  - title: 'Fixed'
    labels:
      - 'bug'
      - 'fix'
  - title: 'Security'
    labels:
      - 'security'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  $CHANGES
