trigger:
  branches:
    include:
    - master
    - refs/tags/*

jobs:
  - job: Android
    condition: eq(variables['Build.Reason'], 'PullRequest')
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
    - task: DownloadSecureFile@1
      name: androidKey
      inputs:
        secureFile: 'key.jks'
    - task: DownloadSecureFile@1
      name: androidKeySettings
      inputs:
        secureFile: 'key.properties'
    - script: |
        echo Installing android key
        sudo cp $(androidKey.secureFilePath) $(Build.SourcesDirectory)
        echo "s/storeFile=\(.*\)/storeFile=$(Build.SourcesDirectory)\/key.jks/g"
        sudo sed "s/storeFile=\(.*\)/storeFile=$(Build.SourcesDirectory)\/key.jks/g" $(androidKeySettings.secureFilePath) > $(Build.SourcesDirectory)/android/key.properties
      displayName: 'InstallingKey'
    - script: |
        git clone -b dev https://github.com/flutter/flutter.git
        export FLUTTER_ROOT=`pwd`/flutter/bin
        export PATH=$FLUTTER_ROOT:$PATH
        flutter channel beta
        flutter doctor
      displayName: 'Flutter Install'
    - script: flutter test
      displayName: 'Flutter Test'
    - script: $(FLUTTER_ROOT)/flutter build apk --split-per-abi -t .\lib\main_prod.dart
      displayName: 'Flutter Build'
    - task: CopyFiles@2
      inputs:
        contents: '**/*.apk'
        targetFolder: '$(build.artifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
