trigger:
  branches:
    include:
    - master
    - refs/tags/*

variables:
  flutter_channel: 'beta'
  flutter_version: '1.20.0-7.4.pre'

pool:
  vmImage: 'macOS-latest'

jobs:
  - job: Test
    steps:
    - script: pip3 install git+https://github.com/eriwen/lcov-to-cobertura-xml.git
      displayName: 'Install lcov-to-cobertura'
    - task: Install-Flutter@0
      inputs:
        channel: $(flutter_channel)
        version: custom
        customVersion: $(flutter_version)
    - script: |
        flutter pub get
        flutter test --coverage --machine > example.jsonl
        flutter pub global activate junitreport
        flutter pub global run junitreport:tojunit --input example.jsonl --output TEST-report.xml
        lcov_cobertura coverage/lcov.info
      displayName: 'Flutter Test'
    - task: PublishTestResults@2
      inputs:
        testResultsFiles: "**/TEST-*.xml"
      condition: succeededOrFailed()
    - task: PublishCodeCoverageResults@1
      inputs:
        codeCoverageTool: Cobertura
        summaryFileLocation: '**/coverage.xml'

  - job: Android
    dependsOn: Test
    condition: or(contains(variables['Build.SourceBranch'], 'master'), contains(variables['Build.SourceBranch'], 'tags'))
    steps:
    - task: DownloadSecureFile@1
      name: androidKey
      inputs:
        secureFile: 'key.jks'
    - task: DownloadSecureFile@1
      name: androidKeySettings
      inputs:
        secureFile: 'key.properties'
    - script: |
        echo Installing android key
        sudo cp $(androidKey.secureFilePath) $(Build.SourcesDirectory)
        echo "s#storeFile=\(.*\)#storeFile=$(Build.SourcesDirectory)/key.jks#g"
        sudo sed "s#storeFile=\(.*\)#storeFile=$(Build.SourcesDirectory)/key.jks#g" $(androidKeySettings.secureFilePath) > $(Build.SourcesDirectory)/android/key.properties
      displayName: 'InstallingKey'
    - task: Install-Flutter@0
      inputs:
        channel: $(flutter_channel)
        version: custom
        customVersion: $(flutter_version)
    - script: flutter build apk --split-per-abi -t ./lib/main_prod.dart
      displayName: 'FlutterBuild APK'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(System.DefaultWorkingDirectory)/build/app/outputs/apk/release'
        artifactName: apk
      displayName: 'Publish APK'

  - job: Web
    dependsOn: Test
    condition: or(contains(variables['Build.SourceBranch'], 'master'), contains(variables['Build.SourceBranch'], 'tags'))
    steps:
    - task: Install-Flutter@0
      inputs:
        channel: $(flutter_channel)
        version: custom
        customVersion: $(flutter_version)
    - script: flutter config --enable-web
      displayName: 'EnableWeb'
    - script: flutter build web -t ./lib/main_prod.dart
      displayName: 'FlutterBuild Web'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(System.DefaultWorkingDirectory)/build/web'
        artifactName: web
      displayName: 'Publish Web'
