trigger:
  branches:
    include:
    - master
    - refs/tags/*

jobs:
  - job: Android
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: FlutterInstall@0
      inputs:
        channel: beta
    - task: FlutterTest@0
      inputs:
        projectDirectory: $(Agent.BuildDirectory)
    - task: FlutterBuild@0
      inputs:
        debugMode: true
        entryPoint: lib/main_dev.dart
        target: apk
        platform: android-arm64
        projectDirectory: $(Agent.BuildDirectory)
    - task: CopyFiles@2
      inputs:
        contents: '**/*.apk'
        targetFolder: '$(build.artifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
