trigger:
  branches:
    include:
    - master
    - refs/tags/*

variables:
  flutter_channel: 'dev'
  flutter_version: 'latest'

pool:
  vmImage: 'macOS-latest'

jobs:
  - job: Test
    steps:
    - script: pip3 install git+https://github.com/eriwen/lcov-to-cobertura-xml.git
      displayName: 'Install lcov-to-cobertura'
    - task: Install-Flutter@0
      inputs:
        channel: $(flutter_channel)
        version: custom
        customVersion: $(flutter_version)
    - script: |
        flutter pub get
        flutter test --coverage --machine > example.jsonl
        flutter pub global activate junitreport
        flutter pub global run junitreport:tojunit --input example.jsonl --output TEST-report.xml
        lcov_cobertura coverage/lcov.info
      displayName: 'Flutter Test'
    - task: PublishTestResults@2
      inputs:
        testResultsFiles: "**/TEST-*.xml"
      condition: succeededOrFailed()
    - task: PublishCodeCoverageResults@1
      inputs:
        codeCoverageTool: Cobertura
        summaryFileLocation: '**/coverage.xml'
