trigger:
  branches:
    include:
    - master
    - refs/tags/*

pool:
  vmImage: 'macOS-latest'

jobs:
  - job: Android
    condition: eq(variables['Build.Reason'], 'PullRequest')
    steps:
    - task: FlutterInstall@0
      inputs:
        channel: beta
    - task: FlutterTest@0
      inputs:
        projectDirectory: $(Build.SourcesDirectory)
    - bash: $(FlutterToolPath)/bin/flutter build apk --split-per-abi -t .\lib\main_prod.dart
      displayName: 'FlutterBuild'
    - task: CopyFiles@2
      inputs:
        contents: '**/*.apk'
        targetFolder: '$(build.artifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
