name: smarthome
description: 智慧家庭
version: 0.9.7+8
homepage: https://github.com/he0119/smart-home-flutter
publish_to: "none"

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.8

  # Dart
  logging: ^1.2.0
  graphql: ^5.1.3
  http: ^1.2.1
  bloc: ^8.1.4
  equatable: ^2.0.5
  json_annotation: ^4.9.0
  enum_to_string: ^2.0.0
  version: ^3.0.2
  tuple: ^2.0.2
  provider: ^6.1.2
  mime: ^1.0.5
  gql: any
  rxdart: ^0.27.0
  http_parser: ^4.0.0

  # Flutter
  flutter_bloc: ^8.1.6
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.0
  quick_actions: ^1.0.7
  android_id: ^0.4.0
  device_info_plus: ^10.1.0
  package_info_plus: ^8.0.0
  share_plus: ^9.0.0
  flutter_keyboard_visibility: ^6.0.0
  photo_view: ^0.15.0
  image_picker: ^1.1.2
  sentry_flutter: ^8.3.0
  flutter_treeview: ^1.0.7+1
  dynamic_color: ^1.7.0
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1

  # Widget
  webview_flutter: ^4.8.0
  datetime_picker_formfield: ^2.0.1
  flutter_markdown_selectionarea: ^0.6.17+1
  cached_network_image: ^3.3.1
  dropdown_search: ^5.0.6
  flutter_sticky_header: ^0.6.5
  extended_sliver: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.7
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.2
  sentry_dart_plugin: ^1.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon.webp
  generate: true

flutter_launcher_icons:
  android: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 24
  web:
    generate: true
  windows:
    generate: true
    icon_size: 256

# https://github.com/getsentry/sentry-dart-plugin
sentry:
  # enabled by default
  upload_debug_symbols: true
  # disabled by default
  upload_sources: true
  # disabled by default
  upload_source_maps: true
