name: smarthome
description: 智慧家庭
version: 0.8.5+7
homepage: https://github.com/he0119/smart-home-flutter
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  cupertino_icons: ^1.0.2

  # Dart
  logging: ^1.0.0
  graphql: ^5.0.0
  http: ^0.13.0
  bloc: ^8.0.2
  equatable: ^2.0.3
  json_annotation: ^4.3.0
  enum_to_string: ^2.0.0
  version: ^3.0.2
  tuple: ^2.0.0
  provider: ^6.0.1
  mime: ^1.0.1
  gql: ^0.13.1
  rxdart: ^0.27.3
  http_parser: ^4.0.0

  # Flutter
  flutter_bloc: ^8.0.1
  shared_preferences: ^2.0.5
  quick_actions: ^0.6.0
  device_info_plus: ^3.1.0
  package_info_plus: ^1.0.0
  url_launcher: ^6.0.2
  flutter_keyboard_visibility: ^5.0.0
  photo_view: ^0.14.0
  image_picker: ^0.8.4
  sentry_flutter: ^6.8.1
  flutter_treeview: ^1.0.6+1

  # Widget
  webview_flutter: ^3.0.0
  datetime_picker_formfield: ^2.0.0
  flutter_markdown: ^0.6.0
  cached_network_image: ^3.0.0
  dropdown_search: ^3.0.0
  flutter_sticky_header: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.0.2
  build_runner: ^2.0.3
  json_serializable: ^6.0.1
  flutter_launcher_icons: ^0.9.0
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon.webp
  generate: true

flutter_icons:
  android: true
  image_path: "assets/icon/icon.png"
