name: smarthome
description: 智慧家庭
version: 0.7.5+5
homepage: https://github.com/he0119/smart-home-flutter
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  cupertino_icons: ^1.0.2

  # Dart
  logging: ^1.0.0
  graphql: ^5.0.0
  http: ^0.13.0
  bloc: ^7.2.1
  equatable: ^2.0.3
  json_annotation: ^4.0.0
  enum_to_string: ^2.0.0
  version: ^2.0.0
  tuple: ^2.0.0
  sentry: 6.0.1

  # Flutter
  flutter_bloc: ^7.3.3
  shared_preferences: ^2.0.5
  quick_actions: ^0.6.0
  device_info_plus: ^3.1.0
  package_info_plus: ^1.0.0
  url_launcher: ^6.0.2
  flutter_keyboard_visibility: ^5.0.0
  photo_view: ^0.13.0
  image_picker: ^0.8.4
  sentry_flutter: ^6.0.0

  # Widget
  webview_flutter: ^2.0.2
  datetime_picker_formfield: ^2.0.0
  flutter_markdown: ^0.6.0
  cached_network_image: ^3.0.0
  dropdown_search: ^1.0.0
  flutter_sticky_header: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.5.0
  build_runner: ^2.0.3
  json_serializable: ^4.1.0
  flutter_launcher_icons: ^0.9.0
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon.webp

flutter_icons:
  android: true
  image_path: "assets/icon/icon.png"
