name: smarthome
description: 智慧家庭
version: 0.9.1+8
homepage: https://github.com/he0119/smart-home-flutter
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  cupertino_icons: ^1.0.2

  # Dependency 'androidx.webkit:webkit:1.5.0' requires 'compileSdkVersion' to be set to 32 or higher.
  # 依赖有冲突，只能等 flutter 支持 33 之后再升级。
  # https://github.com/flutter/flutter/issues/103356
  webview_flutter_android: 2.9.5

  # Dart
  logging: ^1.0.0
  graphql: ^5.1.2-beta.5
  http: ^0.13.0
  bloc: ^8.0.2
  equatable: ^2.0.3
  json_annotation: ^4.6.0
  enum_to_string: ^2.0.0
  version: ^3.0.2
  tuple: ^2.0.0
  provider: ^6.0.1
  mime: ^1.0.1
  gql:
  rxdart: ^0.27.3
  http_parser: ^4.0.0

  # Flutter
  flutter_bloc: ^8.0.1
  shared_preferences: ^2.0.5
  quick_actions: ^1.0.0
  device_info_plus: ^7.0.0
  android_id: ^0.0.8
  package_info_plus: ^3.0.0
  url_launcher: ^6.0.2
  flutter_keyboard_visibility: ^5.0.0
  photo_view: ^0.14.0
  image_picker: ^0.8.4
  sentry_flutter: ^6.0.0
  flutter_treeview: ^1.0.6+1
  dynamic_color: ^1.5.4

  # Widget
  webview_flutter: ^3.0.0
  datetime_picker_formfield: ^2.0.0
  flutter_markdown: ^0.6.0
  cached_network_image: ^3.0.0
  dropdown_search: ^5.0.2
  flutter_sticky_header: ^0.6.0
  extended_sliver: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.0.2
  build_runner: ^2.0.3
  json_serializable: ^6.5.4
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon.webp
  generate: true

flutter_icons:
  android: true
  image_path: "assets/icon/icon.png"
