name: smart_home
description: 智慧家庭
version: 0.7.2+5
homepage: https://github.com/he0119/smart-home-flutter
publish_to: none

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0-nullsafety.2
  cupertino_icons: ^1.0.2

  # Dart
  logging: ^1.0.0
  graphql: ^5.0.0-nullsafety.1+readmefix
  http: ^0.13.0
  bloc: ^7.0.0-nullsafety.3
  equatable: ^2.0.0
  json_annotation: ^4.0.0
  enum_to_string: ^2.0.0-nullsafety.1
  version: ^2.0.0-nullsafety
  tuple: ^2.0.0-nullsafety.0

  # Flutter
  flutter_bloc: ^7.0.0-nullsafety.3
  shared_preferences: '2.0.3'
  quick_actions: ^0.5.0
  device_info_plus: ^1.0.0
  package_info_plus: ^1.0.0
  url_launcher: ^6.0.2
  flutter_keyboard_visibility: ^5.0.0
  intent:
    git:
      url: https://github.com/he0119/intent.git
      ref: feature/second_call

  # Widget
  webview_flutter: ^2.0.2
  datetime_picker_formfield: ^2.0.0
  substring_highlight: ^0.1.2
  flutter_sticky_header: ^0.5.0
  flutter_markdown: ^0.6.0
  cached_network_image: ^3.0.0-nullsafety
  settings_ui:
    git: https://github.com/he0119/flutter-settings-ui.git
  dropdown_search: ^0.4.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.0.0-nullsafety.1
  # build_runner:
  json_serializable: ^4.0.0
  flutter_launcher_icons: ^0.9.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon.webp

flutter_icons:
  android: true
  image_path: "assets/icon/icon.png"
