name: smart_home
description: 智慧家庭
version: 0.7.0+5
homepage: https://github.com/he0119/smart-home-flutter
publish_to: none

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0-nullsafety.2

  # Dart
  logging: ^0.11.4
  graphql: ^4.0.0-beta.5
  http: ^0.12.0+4
  bloc: ^6.1.0
  equatable: ^1.2.5
  json_annotation: ^3.0.0
  enum_to_string: ^1.0.9
  version: ^1.0.3
  tuple: ^1.0.3

  # Flutter
  flutter_bloc: ^6.1.0
  shared_preferences: '>=0.5.7+3 <2.0.0'
  quick_actions: ^0.4.0+2
  device_info_plus: ^0.6.0
  package_info_plus: ^0.6.0
  url_launcher: ^5.4.2
  flutter_keyboard_visibility: ^4.0.0

  # Widget
  webview_flutter: ^1.0.1
  datetime_picker_formfield: ^1.0.0
  substring_highlight: ^0.1.2
  flutter_sticky_header: ^0.5.0
  flutter_markdown: ^0.5.0
  cached_network_image: ^2.4.1
  settings_ui:
    git: https://github.com/he0119/flutter-settings-ui.git
  dropdown_search: ^0.4.8

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^7.1.0
  build_runner: ^1.8.0
  json_serializable: ^3.2.0
  flutter_launcher_icons: ^0.8.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon.webp

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
