name: smarthome
description: 智慧家庭
version: 0.9.4+8
homepage: https://github.com/he0119/smart-home-flutter
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.2

  # Dart
  logging: ^1.0.0
  graphql: ^5.1.2
  http: ^1.0.0
  bloc: ^8.0.2
  equatable: ^2.0.3
  json_annotation: ^4.6.0
  enum_to_string: ^2.0.0
  version: ^3.0.2
  tuple: ^2.0.0
  provider: ^6.0.1
  mime: ^1.0.1
  gql: any
  rxdart: ^0.27.3
  http_parser: ^4.0.0

  # Flutter
  flutter_bloc: ^8.0.1
  shared_preferences: ^2.0.5
  url_launcher: ^6.0.2
  quick_actions: ^1.0.0
  android_id: ^0.3.0
  device_info_plus: ^9.0.0
  package_info_plus: ^5.0.1
  flutter_keyboard_visibility: ^5.4.1
  photo_view: ^0.14.0
  image_picker: ^1.0.1
  sentry_flutter: ^7.4.0
  flutter_treeview: ^1.0.6+1
  dynamic_color: ^1.5.4

  # Widget
  webview_flutter: ^4.2.1
  datetime_picker_formfield: ^2.0.0
  flutter_markdown_selectionarea: ^0.6.0
  cached_network_image: ^3.0.0
  dropdown_search: ^5.0.2
  flutter_sticky_header: ^0.6.0
  extended_sliver: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.0.2
  build_runner: ^2.0.3
  json_serializable: ^6.0.1
  flutter_launcher_icons: ^0.13.0
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon.webp
  generate: true

flutter_launcher_icons:
  android: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 24
  web:
    generate: true
  windows:
    generate: true
