name: smarthome
description: 智慧家庭
version: 0.10.0+8
homepage: https://github.com/he0119/smart-home-flutter
publish_to: "none"

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: "3.32.0" # This must be exact! No ranges allowed.

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.8

  # Dart
  logging: ^1.3.0
  graphql: ^5.2.1
  http: ^1.4.0
  bloc: ^9.0.0
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  enum_to_string: ^2.2.1
  version: ^3.0.2
  tuple: ^2.0.2
  provider: ^6.1.5
  mime: ^2.0.0
  gql: any
  rxdart: any
  http_parser: any

  # Flutter
  flutter_bloc: ^9.1.1
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1
  quick_actions: ^1.1.0
  android_id: ^0.4.0
  device_info_plus: ^11.4.0
  package_info_plus: ^8.3.0
  share_plus: ^11.0.0
  flutter_keyboard_visibility: ^6.0.0
  photo_view: ^0.15.0
  image_picker: ^1.1.2
  sentry_flutter: ^8.14.2
  dynamic_color: ^1.7.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.0.0

  # Widget
  webview_flutter: ^4.12.0
  datetime_picker_formfield: ^2.0.1
  flutter_markdown_selectionarea: ^0.6.17+1
  cached_network_image: ^3.4.1
  dropdown_search: ^6.0.2
  flutter_sticky_header: ^0.8.0
  extended_sliver: ^2.1.3
  animated_tree_view: ^2.3.0

# https://github.com/MisterJimson/flutter_keyboard_visibility/pull/155#issuecomment-2112047514
dependency_overrides:
  flutter_keyboard_visibility_web:
    git:
      url: https://github.com/raldhafiri/flutter_keyboard_visibility.git
      ref: master
      path: flutter_keyboard_visibility_web

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^10.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.5
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  sentry_dart_plugin: ^2.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon.webp
  generate: true

flutter_launcher_icons:
  android: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 24
  web:
    generate: true
  windows:
    generate: true
    icon_size: 256

# https://github.com/getsentry/sentry-dart-plugin
sentry:
  # enabled by default
  upload_debug_symbols: true
  # disabled by default
  upload_sources: true
  # disabled by default
  upload_source_maps: true
