name: smart_home
description: 智慧家庭
version: 0.4.0+2
homepage: https://github.com/he0119/smart-home-flutter

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.16.1

  logging: ^0.11.4

  graphql_flutter: ^3.1.0-beta.7
  http: ^0.12.0+4

  bloc: ^5.0.0
  flutter_bloc: ^5.0.0
  equatable: ^1.1.0
  json_annotation: ^3.0.0

  shared_preferences: '>=0.5.7+3 <2.0.0'
  quick_actions: ^0.4.0+2

  device_info: ^0.4.2+1
  package_info: '>=0.4.0+16 <2.0.0'
  version: ^1.0.3

  url_launcher: ^5.4.2
  webview_flutter: ^0.3.19+9

  datetime_picker_formfield: ^1.0.0
  substring_highlight: ^0.1.2
  flutter_sticky_header: ^0.4.2
  flutter_markdown: ^0.4.2
  cached_network_image: ^2.1.0+1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^6.0.0
  build_runner: ^1.8.0
  json_serializable: ^3.2.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/Icon-512.png
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
