name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  flutter_channel: 'dev'
  flutter_version: '1.24.0-7.0.pre'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1.4.0
        with:
          channel: ${{ env.flutter_channel }}
          flutter-version: ${{ env.flutter_version }}
      - run: flutter pub get
      - run: flutter test
