on: push
name: Test
jobs:
  build:
    name: Flutter Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk --split-per-abi -t .\lib\main_prod.dart
      - run: flutter config --enable-web
      - run: flutter build web -t .\lib\main_prod.dart
      - name: Zip web
        run: |
          zip -r web.zip build/web/*
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            web.zip
            "build/app/outputs/apk/release/*.apk"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
