name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  flutter_channel: 'dev'
  flutter_version: '1.24.0-7.0.pre'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1.4.0
        with:
          channel: ${{ env.flutter_channel }}
          flutter-version: ${{ env.flutter_version }}
      - run: flutter pub get
      - run: flutter test

  android:
    name: Android
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v1
      - name: Decrypt large secret
        run: ./.github/scripts/decrypt_secret.sh
        env:
          LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}
      - uses: subosito/flutter-action@v1.4.0
        with:
          channel: ${{ env.flutter_channel }}
          flutter-version: ${{ env.flutter_version }}
      - run: flutter build apk --split-per-abi -t ./lib/main_prod.dart
      - uses: actions/upload-artifact@v2
        with:
          name: android
          path: ${{ github.workspace }}/build/app/outputs/apk/release/*.apk

  web:
    name: Web
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1.4.0
        with:
          channel: ${{ env.flutter_channel }}
          flutter-version: ${{ env.flutter_version }}
      - run: flutter config --enable-web
      - run: flutter build web -t ./lib/main_prod.dart
      - uses: actions/upload-artifact@v2
        with:
          name: web
          path: ${{ github.workspace }}/build/web

  windows:
    name: Windows
    runs-on: windows-latest
    needs: test
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1.4.0
        with:
          channel: ${{ env.flutter_channel }}
          flutter-version: ${{ env.flutter_version }}
      - run: flutter config --enable-windows-desktop
      - run: flutter build windows -t ./lib/main_prod.dart
      - uses: actions/upload-artifact@v2
        with:
          name: windows
          path: ${{ github.workspace }}/build/windows/runner/Release
